### ISSUE TITLE
Manifest file on docker.io not found

### ISSUE THREAD

**Issue by geekai** [andrey-helldar/laravel-gitlab-ci#11]
Hello,

While I tried to pull the image from docker.io as usual, it suddenly gave the error saying that the manifest file not found. I'm simply running the command: `docker pull helldar/laravel-gitlab-ci:stable`.

Thanks for the help.

**Comment by andrey-helldar** [comment]
Try updating Docker. I have not encountered such a problem before.

![image](https://user-images.githubusercontent.com/10347617/222492243-8dc35934-c9c5-478c-87ba-15845baa6675.png)

![image](https://user-images.githubusercontent.com/10347617/222492553-a710bc69-fbb1-4274-afc1-2bcd9d6a23d9.png)

**Comment by geekai** [comment]
> Try updating Docker. I have not encountered such a problem before.
> 
> ![image](https://user-images.githubusercontent.com/10347617/222492243-8dc35934-c9c5-478c-87ba-15845baa6675.png)
> 
> ![image](https://user-images.githubusercontent.com/10347617/222492553-a710bc69-fbb1-4274-afc1-2bcd9d6a23d9.png)

Hello, I confirm that the issue was solved by upgrading docker. Thanks again!

**Comment by andrey-helldar** [comment]
You're welcome!
